routes/web.php
        Route::get('/admin/setting/currency/getCurrency/{id}', 'Admin\AdminCurrencyController@getCurrency');
        Route::post('/admin/setting/currency/store', 'Admin\AdminCurrencyController@store')->name('admin_currency_store');
        Route::post('/admin/setting/currency/destroy/{id}', 'Admin\AdminCurrencyController@destroy');

        // Property Review Controller Routes
        Route::get('/admin/review', 'Admin\AdminReviewController@index')->name('admin_review');
        Route::post('/admin/review/complete/{id}', 'Admin\AdminReviewController@complete');
        Route::post('/admin/review/dismiss/{id}', 'Admin\AdminReviewController@dismiss');
        Route::post('/admin/review/delete/{id}', 'Admin\AdminReviewController@delete');
        Route::post('/admin/review/getReview/{id}', 'Admin\AdminReviewController@getReview');

        // Users Controller Rutes
        Route::get('/admin/user', 'Admin\AdminUserController@index')->name('admin_users');
        Route::get('/admin/user/autocomplete/', 'Admin\AdminUserController@autocomplete');
        Route::get('/admin/user/userinfo/', 'Admin\AdminUserController@userinfo');
        Route::post('/admin/user/search/', 'Admin\AdminUserController@search')->name('admin_user_search');
        Route::post('/admin/user/destroy/{id}', 'Admin\AdminUserController@destroy');
        Route::post('/admin/user/upgrade/{id}', 'Admin\AdminUserController@upgrade');
        Route::post('/admin/user/massdestroy', 'Admin\AdminUserController@massDestroy');
        Route::post('/admin/user/update', 'Admin\AdminUserController@update')->name('admin_user_update');
        Route::post('/admin/user/activate/{id}', 'Admin\AdminUserController@activate');
        Route::post('/admin/user/deactivate/{id}', 'Admin\AdminUserController@deactivate');

        // User Requests Controller Routes
        Route::get('/admin/user/request', 'Admin\AdminUserRequestController@index')->name('admin_users_request');
        Route::post('/admin/user/request/complete/{id}', 'Admin\AdminUserRequestController@complete');
        Route::post('/admin/user/request/dismiss/{id}', 'Admin\AdminUserRequestController@dismiss');
        Route::post('/admin/user/request/delete/{id}', 'Admin\AdminUserRequestController@delete');

        // User Withdrawal Controller Routes
        Route::get('/admin/owner/withdrawal', 'Admin\AdminWithdrawalController@index')->name('admin_user_withdrawals');
        Route::post('/admin/owner/withdrawal/complete/{id}', 'Admin\AdminWithdrawalController@complete');
        Route::post('/admin/owner/withdrawal/dismiss/{id}', 'Admin\AdminWithdrawalController@dismiss');
        Route::post('/admin/owner/withdrawal/delete/{id}', 'Admin\AdminWithdrawalController@delete');
        Route::post('/admin/owner/withdrawal/details/{id}', 'Admin\AdminWithdrawalController@userInfo');

        // Bookings Controller Routes
        Route::get('/admin/booking', 'Admin\AdminBookingController@index')->name('admin_booking');
        Route::post('/admin/booking/user_details/{id}', 'Admin\AdminBookingController@userInfo');
        Route::post('/admin/booking/delete/{id}', 'Admin\AdminBookingController@delete');
        Route::post('/admin/booking/activate/{id}', 'Admin\AdminBookingController@activate');
        Route::post('/admin/booking/reject/{id}', 'Admin\AdminBookingController@reject');

        // Message Controller Routes
        Route::get('/admin/message', 'Admin\AdminMessageController@index')->name('admin_message');
        Route::get('/admin/message/{id}', 'Admin\AdminMessageController@thread')->name('admin_message_list');
        Route::post('/admin/message/reply/{id}', 'Admin\AdminMessageController@reply')->name('admin_message_reply');
        Route::post('/admin/message/delete/{id}', 'Admin\AdminMessageController@delete');
        Route::post('/admin/message/close/{id}', 'Admin\AdminMessageController@close');

        // Payment Controller Routes
        Route::get('/admin/payment', 'Admin\AdminPaymentController@index')->name('admin_payment');
        Route::post('/admin/payment/details/{id}', 'Admin\AdminPaymentController@details');

        // Translator Controller Routers
        Route::get('/admin/settings/translator', 'Admin\AdminTranslatorController@index')->name('admin_translator');
        Route::post('/admin/settings/translator/getString/{key}', 'Admin\AdminTranslatorController@getString');
        Route::post('/admin/settings/translator/updateString', 'Admin\AdminTranslatorController@updateString');
        Route::post('/admin/settings/translator/createString', 'Admin\AdminTranslatorController@createString')->name('admin_create_string');
        Route::get('/admin/settings/translator/export', 'Admin\AdminLanguageController@export')->name('strings_export');
        Route::post('/admin/settings/translator/import', 'Admin\AdminLanguageController@import')->name('strings_import');

        // Availability Dates Controller Routes
        Route::get('/admin/property/date/{id}', 'Admin\AdminPropertyDateController@index')->name('admin_property_date');
        Route::get('/admin/property/pricing/{id}', 'Admin\AdminPropertyPricingController@index')->name('admin_property_pricing');

        //  Owners Controller Routes
        Route::get('/admin/owner', 'Admin\AdminOwnerController@index')->name('admin_owner');
        Route::get('/admin/owner/edit/{id}', 'Admin\AdminOwnerController@edit')->name('admin_owner_edit');
        Route::post('/admin/owner/update/{id}', 'Admin\AdminOwnerController@update')->name('admin_owner_update');
        Route::post('/admin/owner/activate/{id}', 'Admin\AdminOwnerController@activate');
        Route::post('/admin/owner/deactivate/{id}', 'Admin\AdminOwnerController@deactivate');
        Route::post('/admin/owner/destroy/{id}', 'Admin\AdminOwnerController@delete');
        Route::post('/admin/owner/deleteImage/{id}', 'Admin\AdminOwnerController@deleteImage');
        Route::get('/admin/owner/properties/{id}', 'Admin\AdminOwnerController@allproperties')->name('admin_owner_properties');
        Route::get('/admin/owner/services/{id}', 'Admin\AdminOwnerController@allservices')->name('admin_owner_services');
        Route::get('/admin/owner/activities/{id}', 'Admin\AdminOwnerController@allactivities')->name('admin_owner_activities');
        Route::get('/admin/owner/purchases/{id}', 'Admin\AdminOwnerController@allpurchases')->name('admin_owner_purchases');
        Route::get('/admin/owner/withdrawals/{id}', 'Admin\AdminOwnerController@allwithdrawals')->name('admin_owner_withdrawals');
        Route::get('/admin/owner/autocomplete/', 'Admin\AdminOwnerController@autocomplete');
        Route::post('/admin/owner/search/', 'Admin\AdminOwnerController@search')->name('admin_owner_search');

        // Resource Admin Controllers
        Route::resource('/admin/blog', 'Admin\AdminBlogController', ['as' => 'admin']);
        Route::resource('/admin/page', 'Admin\AdminPageController', ['as' => 'admin']);
        Route::resource('/admin/faq', 'Admin\AdminFaqController', ['as' => 'admin']);
        Route::resource('/admin/service', 'Admin\AdminServiceController', ['as' => 'admin']);
        Route::resource('/admin/taxonomy/category', 'Admin\AdminCategoryController', ['as' => 'admin.taxonomy']);
        Route::resource('/admin/taxonomy/location', 'Admin\AdminLocationController', ['as' => 'admin.taxonomy']);
        Route::resource('/admin/property', 'Admin\AdminPropertyController', ['as' => 'admin']);

    });

    Route::get('/admin', 'Admin\AdminLoginController@index')->name('admin_login');
    Route::get('/admin/reset', 'Admin\AdminLoginController@resetPassword')->name('admin_reset');

// Image Handler
    Route::get('/image_handler', 'ImageHandler@index');
    Route::post('/image_handler/upload', 'ImageHandler@store')->name('image_handler_upload');
    Route::post('/image_handler/delete', 'ImageHandler@delete')->name('image_handler_delete');
    Route::post('/image_handler/deleteBase', 'ImageHandler@deleteBase')->name('image_handler_deleteBase');

    /*
    |--------------------------------------------------------------------------
    | Frontend Routes
    |--------------------------------------------------------------------------
    */

    Route::group(['middleware' => 'user'], function () {

        // Only for users
        Route::get('/my-account', 'UserController@index')->name('my_account');
        Route::post('/user-update', 'UserController@update')->name('user_update');
        Route::post('/user-request', 'UserController@request');

        // Message Controller Routes
        Route::get('/message', 'MessageController@index')->name('message');
        Route::get('/message/{id}', 'MessageController@thread')->name('message_list');
        Route::post('/message/reply/{id}', 'MessageController@reply')->name('message_reply');
        Route::post('/message/post', 'MessageController@post')->name('message_owner');

    });

// Updating Booksi
    Route::get('/update-booksi', 'UpdateController@update');

// Home Routes
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/user/resend', 'UserController@resend')->name('resend_activation_mail');
    Route::post('/user/changeLanguage', 'UserController@changeLanguage')->name('change_language');
    Route::post('/user/changeCurrency', 'UserController@changeCurrency')->name('change_currency');
    Route::get('/user/reset', 'UserController@resetPassword')->name('reset_password');
    Route::post('/user/resend_mail', 'Auth\LoginController@resendMail')->name('resend_activation');
    Route::get('/user/activation/{token}', 'Auth\RegisterController@activateUser')->name('user.activate');
    Route::get('/user-register', 'UserController@register')->name('register')->middleware('logged');
    Route::post('/reCaptcha', 'HomeController@reCaptcha')->name('reCaptcha');
    Route::post('/review', 'HomeController@review')->name('make_review');
    Route::get('/login', 'UserController@login')->name('login')->middleware('logged');

app/Models/Admin/Blog.php
<?php

namespace App\Models\Admin;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{

    // Allow columns to be filled with data
    protected $fillable = [
        'user_id', 'status', 'image', 'alias'
    ];

    // Returning the post's user
    public function user(){
        return $this->belongsTo('App\Models\User');
    }
    
    // Getting the images in the post content
    public function images(){
        return $this->morphMany('App\Models\Image', 'imageable');
    }

    // Getting the content - Default Language
    public function contentDefault(){
        $default = Language::where('default', 1)->first();
        return $this->hasOne('App\Models\Admin\BlogContent')->where('language_id', $default->id);
    }

    // Getting the content all Languages
    public function content($language_id = 1){
        return $this->hasOne('App\Models\Admin\BlogContent')->where('language_id', $language_id)->first();
    }

    // Getting the content all Languages
    public function contentload(){
        return $this->hasOne('App\Models\Admin\BlogContent');
    }

    public function getImageAttribute($value){
        if($value != ''){
            if($value == 'no_image.jpg'){
                return '/images/'. $value;
            }else{
                return '/images/data/'. $value;
            }
        }else{
            return '';
        }
    }

    public function getCreatedAtAttribute($date){
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }

    public function getUpdatedAtAttribute($date){
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }
}

app/Models/Admin/Message.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $fillable = ['message', 'thread_id', 'user'];

    // Return the thread this message belongs
    public function thread(){
    	return $this->belongsTo('App\Models\Admin\MessageThread', 'thread_id');
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin\Message;
use App\Models\Admin\MessageThread;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class MessageController extends Controller
{
    protected $user, $default_language, $static_data;
    public function __construct(){
        $this->user = Auth::user();
        $this->default_language = default_language();
        $this->static_data = static_home();
    }

    public function index(){
        if(get_setting('enable_messages', 'user')){
            $static_data = $this->static_data;
            $default_language = $this->default_language;
            $threads = MessageThread::where('user_id', $this->user->id)->orderBy('closed', 'desc')->orderBy('created_at', 'desc')->paginate(10);
            return view('home.message.index', compact('static_data', 'default_language','threads'));
        }else{
            return redirect()->back();   
        }
    }

    public function thread($id){
        $thread = MessageThread::findOrFail($id);
        if($thread->closed && $thread->user_id != $this->user->id && get_setting('enable_messages', 'user')){
            return redirect()->back();
        }else{
            $static_data = $this->static_data;
            $default_language = $this->default_language;
            $messages = Message::where('thread_id', $id)->orderBy('created_at', 'desc')->get();
            return view('home.message.message', compact('static_data', 'default_language', 'thread', 'messages'));
        }
    }

    public function reply(Request $request, $id){
        $thread = MessageThread::findOrFail($id);
        $thread->status = 1;

        if($thread->owner && $thread->user){
            // Create the Message
            $data['thread_id'] = $thread->id;
            $data['user'] = 1;
            $data['message'] = $request->message;
            Message::create($data);

            // Mailing
            $static_data = static_home();
            $mail_data['message_received'] = $static_data['strings']['message_received'];
            $mail_data['message_received'] = $static_data['strings']['message_received'];
            $mail_data['str_from'] = $static_data['strings']['from'];
            $mail_data['from'] = $thread->user ? $thread->user->username : '';
            $mail_data['email'] = $thread->owner ? $thread->owner->email : '';
            $mail_data['first_name'] = $thread->owner ? $thread->owner->info->first_name : '';
            $mail_data['message_login_to_reply'] = $static_data['strings']['message_login_to_reply'];
            $mail_data['regards'] = $static_data['strings']['regards'];
            $mail_data['site_name'] = $static_data['site_settings']['site_name'];
            $mail_data['admin_email'] = $static_data['site_settings']['contact_email'];

            // Create the mail and send it
            Mail::send('emails.message', ['mail_data' => $mail_data], function ($m) use ($mail_data) {
                $m->from($mail_data['admin_email'], $mail_data['site_name']);
                $m->to($mail_data['email'], $mail_data['first_name'])->subject($mail_data['message_received'] .' - '. $mail_data['site_name']);
            });

            $thread->touch();
            $thread->save();
            Session::flash('success_message_sent', true);
            return redirect()->route('message');
        }else{
            return redirect()->route('message');
        }
    }

    public function post(Request $request){
        $data['status'] = 1;
        $data['owner_id'] = $request->owner_id;
        $data['user_id'] = $request->user_id;
        $data['closed'] = 0;

        $thread = MessageThread::where('closed', 0)->where('user_id', $data['user_id'])->where('owner_id', $data['owner_id'])->first();
        if(!$thread){ // If there is no open thread, create one
            $thread = MessageThread::create($data);
        }

        if($thread->owner && $thread->user){
            // Create the Message
            $data['thread_id'] = $thread->id;
            $data['user'] = 1;
            $data['message'] = $request->message;
            Message::create($data);

            // Mailing
            $static_data = $this->static_data;
            $mail_data['message_received'] = $static_data['strings']['message_received'];
            $mail_data['message_received'] = $static_data['strings']['message_received'];
            $mail_data['str_from'] = $static_data['strings']['from'];
            $mail_data['from'] = $thread->user ? $thread->user->username : '';
            $mail_data['email'] = $thread->owner ? $thread->owner->email : '';
            $mail_data['first_name'] = $thread->owner ? $thread->owner->info->first_name : '';
            $mail_data['message_login_to_reply'] = $static_data['strings']['message_login_to_reply'];
            $mail_data['regards'] = $static_data['strings']['regards'];
            $mail_data['site_name'] = $static_data['site_settings']['site_name'];
            $mail_data['admin_email'] = $static_data['site_settings']['contact_email'];

            // Create the mail and send it
            Mail::send('emails.message', ['mail_data' => $mail_data], function ($m) use ($mail_data) {
                $m->from($mail_data['admin_email'], $mail_data['site_name']);
                $m->to($mail_data['email'], $mail_data['first_name'])->subject($mail_data['message_received'] .' - '. $mail_data['site_name']);
            });

            $thread->touch();
            $thread->save();
            Session::flash('success_message_sent', true);
            return redirect()->route('message');
        }else{
            return redirect()->route('message');
        }
    }
}

resources/views/admin/message/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>{{get_string('messages') . ' - ' . get_setting('site_name', 'site')}}</title>
@endsection
@section('content')
@section('page_title')
    <h3 class="page-title mbot10">{{get_string('message_threads')}}</h3>
@endsection
 @if(Session::has('success_message_sent'))
    <div class="col s12">
        <div class="col s12 text-centered">
            <h5 class="color-primary">{{ get_string('success_message_sent') }}</h5>
        </div>
    </div>
 @endif
<div class="col s12">
    @if($threads->count())
        <div class="table-responsive">
            <table class="table bordered striped">
                <thead class="thead-inverse">
                <tr>
                    <th>
                        <input type="checkbox" class="filled-in primary-color" id="select-all" />
                        <label for="select-all"></label>
                    </th>
                    <th>{{get_string('between')}}</th>
                    <th>{{get_string('updated')}}</th>
                    <th>{{get_string('created')}}</th>
                    <th class="icon-options">{{get_string('options')}}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($threads as $thread)
                    <tr class="{{ $thread->closed ? 'disabled-style' : '' }}">
                        <td>
                            <input type="checkbox" class="filled-in primary-color" id="{{$thread->id}}" />
                            <label for="{{$thread->id}}"></label>
                        </td>
                        <td @if($thread->status == 1) class="color-red" @endif>
                            {{$thread->user ? $thread->user->username : '' }} - {{  $thread->owner ? $thread->owner->username : '' }}</td>
                        <td>{{ $thread->updated_at->diffForHumans() }}</td>
                        <td>{{ $thread->created_at->diffForHumans() }}</td>
                        <td>
                            <div class="icon-options">
                                @if(!$thread->closed) 
                                    <a class="edit-button" href="{{route('admin_message_list', $thread->id)}}"><i class="small material-icons color-primary">message</i></a>
                                <a href="#" class="close-button" data-id="{{$thread->id}}"><i class="small material-icons color-red">close</i></a>
                                @endif
                                <a href="#" class="delete-button" data-id="{{$thread->id}}"><i class="small material-icons color-red">delete</i></a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{$threads->links()}}
    @else
        <strong class="center-align">{{get_string('no_results')}}</strong>
    @endif
</div>
<input type="hidden" class="token" value="{{ csrf_token() }}">
@endsection

@section('footer')
<script type="text/javascript">
    $(document).ready(function(){

         $('.close-button').click(function(event){
            event.preventDefault();
            var id = $(this).data('id');
            var selector = $(this).parents('tr');
            var status = $('.booking-status', selector);
            var token = $('.token').val();
            if(!selector.hasClass('disabled-style')) {
                bootbox.confirm({
                    title: '{{get_string('confirm_action')}}',
                    message: '{{get_string('message_close_confirm')}}',
                    onEscape: true,
                    backdrop: true,
                    buttons: {
                        cancel: {
                            label: '{{get_string('no')}}',
                            className: 'btn waves-effect'
                        },
                        confirm: {
                            label: '{{get_string('yes')}}',
                            className: 'btn waves-effect'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            $.ajax({
                                url: '{{ url('/admin/message/close') }}/' + id,
                                type: 'post',
                                data: {_token: token},
                                beforeSend: function(){
                                    $('.table').addClass('loading');
                                },
                                success: function (msg) {
                                    selector.addClass('disabled-style');
                                    status.html('{{get_string('yes')}}');
                                    toastr.success(msg);
                                    $('.close-button').hide();
                                    $('.edit-button').hide();
                                    $('.table').removeClass('loading');
                                },
                                error: function (msg) {
                                    toastr.error(msg.responseJSON);
                                    $('.table').removeClass('loading');
                                }
                            });
                        }
                    }
                });
            }
        });

        $('.delete-button').click(function(event){
            event.preventDefault();
            var id = $(this).data('id');
            var selector = $(this).parents('tr');
            var token = $('.token').val();
            bootbox.confirm({
                title: '{{get_string('confirm_action')}}',
                message: '{{get_string('delete_confirm')}}',
                onEscape: true,
                backdrop: true,
                buttons: {
                    cancel: {
                        label: '{{get_string('no')}}',
                        className: 'btn waves-effect'
                    },
                    confirm: {
                        label: '{{get_string('yes')}}',
                        className: 'btn waves-effect'
                    }
                },
                callback: function (result) {
                    if(result){
                        $.ajax({
                            url: '{{ url('/admin/message/delete') }}/'+id,
                            type: 'post',
                            data: {_token :token},
                            success:function(msg) {
                                selector.remove();
                                toastr.success(msg);
                            },
                            error:function(msg){
                                toastr.error(msg.responseJSON);
                            }
                        });
                    }
                }
            });
        });
    });
</script>
@endsection

resources/views/admin/message/message.blade.php
@extends('layouts.admin')

@section('title')
    <title>{{get_string('messages') . ' - ' . get_setting('site_name', 'site')}}</title>
@endsection
@section('content')
@section('page_title')
    <h3 class="page-title mbot10">{{get_string('messages')}}</h3>
@endsection
<div class="col s12">
    {!! Form::open(['method' => 'post', 'url' => route('admin_message_reply', $thread->id)]) !!}
    <div class="form-group">
        {!! Form::textarea('message', null, ['class' => 'form-control', 'required', 'placeholder' => get_string('write_your_message')]) !!}
    </div>
    <button class="btn waves-effect" type="submit" name="action">{{get_string('reply')}}</button>
    {!! Form::close() !!}
</div>
<div class="col s12">
    <h3 class="page-title mbot10">{{get_string('messages')}}</h3>
    <div id="messages">
        @foreach($messages as $message)
            <div class="message {{ $message->user ? 'user-message' : 'owner-message' }} ">{{ $message->message }}</div>
        @endforeach  
    </div>
</div>
<input type="hidden" class="token" value="{{ csrf_token() }}">
@endsection